apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "django-deepface-demo.fullname" . }}-media
  labels:
    {{- include "django-deepface-demo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.django.media.size }}
  {{- if .Values.django.media.storageClass }}
  storageClassName: {{ .Values.django.media.storageClass }}
  {{- end }}