apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-deepface-demo.fullname" . }}
  labels:
    {{- include "django-deepface-demo.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | default (randAlphaNum 50) | b64enc | quote }}
  {{- if .Values.django.database.external }}
  DATABASE_PASSWORD: {{ .Values.django.database.password | b64enc | quote }}
  {{- else }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  {{- end }}