# Generated by Django 5.2.1 on 2025-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaptureDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.TextField()),
                ("browser", models.CharField(max_length=100)),
                ("os", models.CharField(max_length=100)),
                ("device_type", models.CharField(max_length=50)),
                ("engine", models.CharField(max_length=50)),
                ("was_successful", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
