# Generated by Django 5.2.1 on 2025-05-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_deepface_demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturedevice",
            name="browser",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="capturedevice",
            name="device_type",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="capturedevice",
            name="engine",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="capturedevice",
            name="os",
            field=models.CharField(max_length=150),
        ),
    ]
