# Generated by Django 5.2.1 on 2025-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_deepface_demo", "0002_alter_capturedevice_browser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturedevice",
            name="browser_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="capturedevice",
            name="device_brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="capturedevice",
            name="device_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="capturedevice",
            name="os_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="capturedevice",
            name="browser",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="capturedevice",
            name="device_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="capturedevice",
            name="engine",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="capturedevice",
            name="os",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="capturedevice",
            name="was_successful",
            field=models.BooleanField(default=False),
        ),
    ]
