# Generated by Django 5.2.1 on 2025-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_deepface_demo", "0003_capturedevice_browser_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturedevice",
            name="stage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
